name: Code quality issue
description: Suggest improvements to the CrissCross codebase
labels:
  - chore
body:
  - type: textarea
    id: reasons
    attributes:
      label: Describe the issue
      description: What are the code quality issues and how would you like to see them solved?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative solutions
      description: Are there any alternative solutions you've considered?
  - type: textarea
    id: additional-info
    attributes:
      label: Additional information
      description: Is there anything else you would like to tell us?
